function varargout = PsychNanoVG(varargin)  %#ok<STOUT>
%PsychNanoVG  NanoVG vector graphics inside a Psychtoolbox window.
%
%   This file is the help text and the fallback when the MEX file
%   is missing. When the MEX is on the path it takes precedence.
%
%   Every call takes a subcommand name, or the numeric opcode from
%   PsychNanoVGOp, as the first argument. Call every subcommand
%   between Screen('BeginOpenGL') and Screen('EndOpenGL').
%
%   Version: 0.1.0+nanovg.ce3bf745eb2d
%
%   --- Batch ---
%%     Circles                  PsychNanoVG('Circles', cxyr). Nx3 double or single. One Circle...
%%     Path                     PsychNanoVG('Path', cmds). cmds is an Nx7 matrix with a command...
%%     Polygon                  PsychNanoVG('Polygon', xy). Polyline with the path closed.
%%     Polyline                 PsychNanoVG('Polyline', xy [, close=false]). xy is Nx2 double or...
%%     Rects                    PsychNanoVG('Rects', xywh). Nx4 double or single, one Rect per row.
%%     StrokeSegments           PsychNanoVG('StrokeSegments', seg, rgba). seg is Nx4 [x0 y0 x1...
%
%   --- Colors ---
%%     HSL                      Returns color value specified by hue, saturation and lightness....
%%     HSLA                     Returns color value specified by hue, saturation and lightness...
%%     LerpRGBA                 Linearly interpolates from color c0 to c1, and returns resulting...
%%     RGB                      Color utils Colors in NanoVG are stored as unsigned ints in ABGR...
%%     RGBA                     Returns a color value from red, green, blue and alpha values.
%%     RGBAf                    Returns a color value from red, green, blue and alpha values.
%%     RGBf                     Returns a color value from red, green, blue values. Alpha will...
%%     TransRGBA                Sets transparency of a color value.
%%     TransRGBAf               Sets transparency of a color value.
%
%   --- Images ---
%%     CreateImage              Images NanoVG allows you to load jpg, png, psd, tga, pic and gif...
%%     CreateImageMem           Creates image by loading it from the specified chunk of memory....
%%     CreateImageRGBA          Creates image from specified image data. Returns handle to the...
%%     DeleteImage              Deletes created image.
%%     ImageSize                Returns the dimensions of a created image.
%%     UpdateImage              Updates image data specified by image handle.
%
%   --- Lifecycle ---
%%     BeginFrame               PsychNanoVG('BeginFrame', w, h [, pixelRatio=1]). Saves the...
%%     CancelFrame              PsychNanoVG('CancelFrame'). Drops the current frame without...
%%     EndFrame                 PsychNanoVG('EndFrame'). Flushes the frame to GL, restores the...
%%     Enum                     v = PsychNanoVG('Enum', 'NVG_ALIGN_CENTER'). Looks up a NanoVG...
%%     FindSystemFont           path = PsychNanoVG('FindSystemFont', 'Arial'). Searches the...
%%     Init                     PsychNanoVG('Init' [, opts]). Loads GL entry points and creates...
%%     Opcode                   op = PsychNanoVG('Opcode', 'LineTo'). The numeric opcode of a...
%%     Shutdown                 PsychNanoVG('Shutdown'). Deletes render targets, images, fonts,...
%%     Stats                    s = PsychNanoVG('Stats' [, 'reset']). Per subcommand calls,...
%%     Version                  v = PsychNanoVG('Version'). Struct with nanovg, psychnanovg,...
%
%   --- Paints ---
%%     BoxGradient              Creates and returns a box gradient. Box gradient is a feathered...
%%     ImagePattern             Creates and returns an image pattern. Parameters (ox,oy) specify...
%%     LinearGradient           Paints NanoVG supports four types of paints: linear gradient,...
%%     PaintDelete              PsychNanoVG('PaintDelete', paint). Frees one paint table entry.
%%     RadialGradient           Creates and returns a radial gradient. Parameters (cx,cy)...
%
%   --- Paths ---
%%     Arc                      Creates new circle arc shaped sub-path. The arc center is at...
%%     ArcTo                    Adds an arc segment at the corner defined by the last path...
%%     BeginPath                Paths Drawing a new shape starts with nvgBeginPath(), it clears...
%%     BezierTo                 Adds cubic bezier segment from last point in the path via two...
%%     Circle                   Creates new circle shaped sub-path.
%%     ClosePath                Closes current sub-path with a line segment.
%%     Ellipse                  Creates new ellipse shaped sub-path.
%%     Fill                     Fills the current path with current fill style.
%%     LineTo                   Adds line segment from the last point in the path to the...
%%     MoveTo                   Starts new sub-path with specified point as first point.
%%     PathWinding              Sets the current sub-path winding, see NVGwinding and NVGsolidity.
%%     QuadTo                   Adds quadratic bezier segment from last point in the path via a...
%%     Rect                     Creates new rectangle shaped sub-path.
%%     RoundedRect              Creates new rounded rectangle shaped sub-path.
%%     RoundedRectVarying       Creates new rounded rectangle shaped sub-path with varying radii...
%%     Stroke                   Fills the current path with current stroke style.
%
%   --- Render styles ---
%%     FillColor                Sets current fill style to a solid color.
%%     FillPaint                Sets current fill style to a paint, which can be a one of the...
%%     GlobalAlpha              Sets the transparency applied to all rendered shapes. Already...
%%     GlobalCompositeBlendFunc Sets the composite operation with custom pixel arithmetic. The...
%%     GlobalCompositeBlendFuncSeparate Sets the composite operation with custom pixel arithmetic for...
%%     GlobalCompositeOperation Composite operation The composite operations in NanoVG are...
%%     LineCap                  Sets how the end of the line (cap) is drawn, Can be one of:...
%%     LineJoin                 Sets how sharp path corners are drawn. Can be one of NVG_MITER...
%%     MiterLimit               Sets the miter limit of the stroke style. Miter limit controls...
%%     ShapeAntiAlias           Render styles Fill and stroke render style can be either a solid...
%%     StrokeColor              Sets current stroke style to a solid color.
%%     StrokePaint              Sets current stroke style to a paint, which can be a one of the...
%%     StrokeWidth              Sets the stroke width of the stroke style.
%
%   --- Scissoring ---
%%     IntersectScissor         Intersects current scissor rectangle with the specified...
%%     ResetScissor             Reset and disables scissoring.
%%     Scissor                  Scissoring Scissoring allows you to clip the rendering into a...
%
%   --- State ---
%%     Reset                    Resets current render state to default values. Does not affect...
%%     Restore                  Pops and restores current render state.
%%     Save                     State Handling NanoVG contains state which represents how paths...
%
%   --- Targets ---
%%     CreateImageFromTexture   img = PsychNanoVG('CreateImageFromTexture', glTexId, w, h [,...
%%     RenderTargetBind         PsychNanoVG('RenderTargetBind', rt). Binds the target...
%%     RenderTargetCreate       [rt, glTexId] = PsychNanoVG('RenderTargetCreate', w, h [,...
%%     RenderTargetDelete       PsychNanoVG('RenderTargetDelete', rt).
%%     RenderTargetImage        img = PsychNanoVG('RenderTargetImage', rt). The NanoVG image id...
%%     RenderTargetUnbind       PsychNanoVG('RenderTargetUnbind'). Rebinds the framebuffer that...
%
%   --- Text ---
%%     AddFallbackFont          Adds a fallback font by name.
%%     AddFallbackFontId        Adds a fallback font by handle.
%%     CreateFont               Text NanoVG allows you to load .ttf files and use the font to...
%%     CreateFontAtIndex        fontIndex specifies which font face to load from a .ttf/.ttc file.
%%     CreateFontMem            Creates font by loading it from the specified memory chunk....
%%     CreateFontMemAtIndex     fontIndex specifies which font face to load from a .ttf/.ttc file.
%%     FindFont                 Finds a loaded font of specified name, and returns handle to it,...
%%     FontBlur                 Sets the blur of current text style.
%%     FontFace                 Sets the font face based on specified name of current text style.
%%     FontFaceId               Sets the font face based on specified id of current text style.
%%     FontSize                 Sets the font size of current text style.
%%     ResetFallbackFonts       PsychNanoVG('ResetFallbackFonts', baseFont). Drops the fallback...
%%     ResetFallbackFontsId     Resets fallback fonts by handle.
%%     Text                     Draws text string at specified location. If end is specified...
%%     TextAlign                Sets the text align of current text style, see NVGalign for options.
%%     TextBounds               Measures the specified text string. Parameter bounds should be a...
%%     TextBox                  Draws multi-line text string at specified location wrapped at...
%%     TextBoxBounds            Measures the specified multi-text string. Parameter bounds...
%%     TextBreakLines           Breaks the specified text into lines. If end is specified only...
%%     TextGlyphPositions       Calculates the glyph x positions of the specified text. If end...
%%     TextLetterSpacing        Sets the letter spacing of current text style.
%%     TextLineHeight           Sets the proportional line height of current text style. The...
%%     TextMetrics              Returns the vertical metrics based on the current text style....
%
%   --- Transform helpers ---
%%     DegToRad                 Converts degrees to radians and vice versa.
%%     RadToDeg                 RadToDeg.
%%     TransformIdentity        The following functions can be used to make calculations on 2x3...
%%     TransformInverse         Sets the destination to inverse of specified transform. Returns...
%%     TransformMultiply        Sets the transform to the result of multiplication of two...
%%     TransformPoint           Transform a point by given transform.
%%     TransformPremultiply     Sets the transform to the result of multiplication of two...
%%     TransformRotate          Sets the transform to rotate matrix. Angle is specified in radians.
%%     TransformScale           Sets the transform to scale matrix.
%%     TransformSkewX           Sets the transform to skew-x matrix. Angle is specified in radians.
%%     TransformSkewY           Sets the transform to skew-y matrix. Angle is specified in radians.
%%     TransformTranslate       Sets the transform to translation matrix matrix.
%
%   --- Transforms ---
%%     CurrentTransform         Stores the top part (a-f) of the current transformation matrix...
%%     ResetTransform           Transforms The paths, gradients, patterns and scissor region are...
%%     Rotate                   Rotates current coordinate system. Angle is specified in radians.
%%     Scale                    Scales the current coordinate system.
%%     SkewX                    Skews the current coordinate system along X axis. Angle is...
%%     SkewY                    Skews the current coordinate system along Y axis. Angle is...
%%     Transform                Premultiplies current coordinate system by specified matrix. The...
%%     Translate                Translates current coordinate system.
%
%   See also PsychNanoVGOp, PsychNanoVGFonts, PsychNanoVGDemo,
%   PsychNanoVGPolylineGradient.

msg = ['The PsychNanoVG MEX file is not on the path. ', ...
       'Run build, then call PsychNanoVGSetup, which adds ', ...
       'dist/<arch> ahead of this directory.'];
error('psychnanovg:NotBuilt', '%s', msg);
end
