function test_gen_marshal()
%TEST_GEN_MARSHAL  Call every generated subcommand once.
%
%   Runs with Init renderer 'null', so no GPU is needed. The test
%   checks that each generated subcommand accepts the argument
%   shapes the generator promised and returns outputs of the
%   promised size and class.
%
%   Generated by gen/generate.py from third_party/nanovg/src/nanovg.h.
%   Do not edit. Run `build.m gen` to regenerate.

    PsychNanoVG('Init', struct('renderer', 'null'));
    c = onCleanup(@() PsychNanoVG('Shutdown'));
    img = PsychNanoVG('CreateImageRGBA', 0, zeros(8, 8, 4, 'uint8'));
    PsychNanoVG('BeginFrame', 640, 480);
    pnt = PsychNanoVG('LinearGradient', 0, 0, 10, 10, [1 0 0 1], [0 0 1 1]);
    %% A real font is needed because fontstash dereferences the
    %% font id without checking it. Machines with no TrueType
    %% font at all skip the calls that take one.
    fnt = -1;
    fontFile = PsychNanoVGFonts('FindSystemFont', 'Arial');
    if isempty(fontFile)
        fontFile = PsychNanoVGFonts('FindSystemFont', 'DejaVuSans');
    end
    if ~isempty(fontFile)
        fnt = PsychNanoVG('CreateFont', 'sans', fontFile);
    end
    tst('ok', 'gen CreateFont', fnt >= 0 || isempty(fontFile));

    % value = PsychNanoVG('AddFallbackFont', baseFont, fallbackFont)
    tcall('AddFallbackFont', {'abc', 'abc'}, {[1, 1]});
    % value = PsychNanoVG('AddFallbackFontId', baseFont, fallbackFont)
    if fnt >= 0, tcall('AddFallbackFontId', {fnt, fnt}, {[1, 1]}); end
    % PsychNanoVG('Arc', cx, cy, r, a0, a1, dir)
    tcall('Arc', {1, 1, 1, 1, 1, 1}, {});
    % PsychNanoVG('ArcTo', x1, y1, x2, y2, radius)
    tcall('ArcTo', {1, 1, 1, 1, 1}, {});
    % PsychNanoVG('BeginPath')
    tcall('BeginPath', {}, {});
    % PsychNanoVG('BezierTo', c1x, c1y, c2x, c2y, x, y)
    tcall('BezierTo', {1, 1, 1, 1, 1, 1}, {});
    % paint = PsychNanoVG('BoxGradient', x, y, w, h, r, f, icol, ocol)
    tcall('BoxGradient', {1, 1, 1, 1, 1, 1, [1 0.5 0.25 1], [1 0.5 0.25 1]}, {[1, 1]});
    % PsychNanoVG('Circle', cx, cy, r)
    tcall('Circle', {1, 1, 1}, {});
    % PsychNanoVG('ClosePath')
    tcall('ClosePath', {}, {});
    % CreateFont takes a file path; covered by tests/gl.
    % CreateFontAtIndex takes a file path; covered by tests/gl.
    % value = PsychNanoVG('CreateFontMem', name, data)
    tcall('CreateFontMem', {'abc', uint8(1:32)}, {[1, 1]});
    % value = PsychNanoVG('CreateFontMemAtIndex', name, data, fontIndex)
    tcall('CreateFontMemAtIndex', {'abc', uint8(1:32), 0}, {[1, 1]});
    % CreateImage takes a file path; covered by tests/gl.
    % CreateImageMem is covered by test_dispatch, not here.
    % value = PsychNanoVG('CreateImageRGBA', imageFlags, data)
    tcall('CreateImageRGBA', {0, zeros(8, 8, 4, 'uint8')}, {[1, 1]});
    % xform = PsychNanoVG('CurrentTransform')
    tcall('CurrentTransform', {}, {[1, 6]});
    % value = PsychNanoVG('DegToRad', deg)
    tcall('DegToRad', {1}, {[1, 1]});
    % DeleteImage is covered by test_dispatch, not here.
    % PsychNanoVG('Ellipse', cx, cy, rx, ry)
    tcall('Ellipse', {1, 1, 1, 1}, {});
    % PsychNanoVG('Fill')
    tcall('Fill', {}, {});
    % PsychNanoVG('FillColor', color)
    tcall('FillColor', {[1 0.5 0.25 1]}, {});
    % PsychNanoVG('FillPaint', paint)
    tcall('FillPaint', {pnt}, {});
    % value = PsychNanoVG('FindFont', name)
    tcall('FindFont', {'abc'}, {[1, 1]});
    % PsychNanoVG('FontBlur', blur)
    tcall('FontBlur', {1}, {});
    % PsychNanoVG('FontFace', font)
    tcall('FontFace', {'abc'}, {});
    % PsychNanoVG('FontFaceId', font)
    if fnt >= 0, tcall('FontFaceId', {fnt}, {}); end
    % PsychNanoVG('FontSize', size)
    tcall('FontSize', {1}, {});
    % PsychNanoVG('GlobalAlpha', alpha)
    tcall('GlobalAlpha', {1}, {});
    % PsychNanoVG('GlobalCompositeBlendFunc', sfactor, dfactor)
    tcall('GlobalCompositeBlendFunc', {2, 2}, {});
    % PsychNanoVG('GlobalCompositeBlendFuncSeparate', srcRGB, dstRGB, srcAlpha, dstAlpha)
    tcall('GlobalCompositeBlendFuncSeparate', {2, 2, 2, 2}, {});
    % PsychNanoVG('GlobalCompositeOperation', op)
    tcall('GlobalCompositeOperation', {0}, {});
    % color = PsychNanoVG('HSL', h, s, l)
    tcall('HSL', {1, 1, 1}, {[1, 4]});
    % color = PsychNanoVG('HSLA', h, s, l, a)
    tcall('HSLA', {1, 1, 1, 128}, {[1, 4]});
    % paint = PsychNanoVG('ImagePattern', ox, oy, ex, ey, angle, image, alpha)
    tcall('ImagePattern', {1, 1, 1, 1, 1, img, 1}, {[1, 1]});
    % wh = PsychNanoVG('ImageSize', image)
    tcall('ImageSize', {img}, {[1, 2]});
    % PsychNanoVG('IntersectScissor', x, y, w, h)
    tcall('IntersectScissor', {1, 1, 1, 1}, {});
    % color = PsychNanoVG('LerpRGBA', c0, c1, u)
    tcall('LerpRGBA', {[1 0.5 0.25 1], [1 0.5 0.25 1], 1}, {[1, 4]});
    % PsychNanoVG('LineCap', cap)
    tcall('LineCap', {0}, {});
    % PsychNanoVG('LineJoin', join)
    tcall('LineJoin', {0}, {});
    % PsychNanoVG('LineTo', x, y)
    tcall('LineTo', {1, 1}, {});
    % paint = PsychNanoVG('LinearGradient', sx, sy, ex, ey, icol, ocol)
    tcall('LinearGradient', {1, 1, 1, 1, [1 0.5 0.25 1], [1 0.5 0.25 1]}, {[1, 1]});
    % PsychNanoVG('MiterLimit', limit)
    tcall('MiterLimit', {1}, {});
    % PsychNanoVG('MoveTo', x, y)
    tcall('MoveTo', {1, 1}, {});
    % PsychNanoVG('PathWinding', dir)
    tcall('PathWinding', {1}, {});
    % PsychNanoVG('QuadTo', cx, cy, x, y)
    tcall('QuadTo', {1, 1, 1, 1}, {});
    % color = PsychNanoVG('RGB', r, g, b)
    tcall('RGB', {128, 128, 128}, {[1, 4]});
    % color = PsychNanoVG('RGBA', r, g, b, a)
    tcall('RGBA', {128, 128, 128, 128}, {[1, 4]});
    % color = PsychNanoVG('RGBAf', r, g, b, a)
    tcall('RGBAf', {1, 1, 1, 1}, {[1, 4]});
    % color = PsychNanoVG('RGBf', r, g, b)
    tcall('RGBf', {1, 1, 1}, {[1, 4]});
    % value = PsychNanoVG('RadToDeg', rad)
    tcall('RadToDeg', {1}, {[1, 1]});
    % paint = PsychNanoVG('RadialGradient', cx, cy, inr, outr, icol, ocol)
    tcall('RadialGradient', {1, 1, 1, 1, [1 0.5 0.25 1], [1 0.5 0.25 1]}, {[1, 1]});
    % PsychNanoVG('Rect', x, y, w, h)
    tcall('Rect', {1, 1, 1, 1}, {});
    % PsychNanoVG('Reset')
    tcall('Reset', {}, {});
    % PsychNanoVG('ResetFallbackFontsId', baseFont)
    if fnt >= 0, tcall('ResetFallbackFontsId', {fnt}, {}); end
    % PsychNanoVG('ResetScissor')
    tcall('ResetScissor', {}, {});
    % PsychNanoVG('ResetTransform')
    tcall('ResetTransform', {}, {});
    % PsychNanoVG('Restore')
    tcall('Restore', {}, {});
    % PsychNanoVG('Rotate', angle)
    tcall('Rotate', {1}, {});
    % PsychNanoVG('RoundedRect', x, y, w, h, r)
    tcall('RoundedRect', {1, 1, 1, 1, 1}, {});
    % PsychNanoVG('RoundedRectVarying', x, y, w, h, radTopLeft, radTopRight, radBottomRight, radBottomLeft)
    tcall('RoundedRectVarying', {1, 1, 1, 1, 1, 1, 1, 1}, {});
    % PsychNanoVG('Save')
    tcall('Save', {}, {});
    % PsychNanoVG('Scale', x, y)
    tcall('Scale', {1, 1}, {});
    % PsychNanoVG('Scissor', x, y, w, h)
    tcall('Scissor', {1, 1, 1, 1}, {});
    % PsychNanoVG('ShapeAntiAlias', enabled)
    tcall('ShapeAntiAlias', {1}, {});
    % PsychNanoVG('SkewX', angle)
    tcall('SkewX', {1}, {});
    % PsychNanoVG('SkewY', angle)
    tcall('SkewY', {1}, {});
    % PsychNanoVG('Stroke')
    tcall('Stroke', {}, {});
    % PsychNanoVG('StrokeColor', color)
    tcall('StrokeColor', {[1 0.5 0.25 1]}, {});
    % PsychNanoVG('StrokePaint', paint)
    tcall('StrokePaint', {pnt}, {});
    % PsychNanoVG('StrokeWidth', size)
    tcall('StrokeWidth', {1}, {});
    % value = PsychNanoVG('Text', x, y, string)
    tcall('Text', {1, 1, 'abc'}, {[1, 1]});
    % PsychNanoVG('TextAlign', align)
    tcall('TextAlign', {1}, {});
    % [value, bounds] = PsychNanoVG('TextBounds', x, y, string)
    tcall('TextBounds', {1, 1, 'abc'}, {[1, 1], [1, 4]});
    % PsychNanoVG('TextBox', x, y, breakRowWidth, string)
    tcall('TextBox', {1, 1, 1, 'abc'}, {});
    % bounds = PsychNanoVG('TextBoxBounds', x, y, breakRowWidth, string)
    tcall('TextBoxBounds', {1, 1, 1, 'abc'}, {[1, 4]});
    % [value, rows] = PsychNanoVG('TextBreakLines', string, breakRowWidth, [maxRows])
    tcall('TextBreakLines', {'abc', 1, 8}, {[1, 1], []});
    % [value, positions] = PsychNanoVG('TextGlyphPositions', x, y, string)
    tcall('TextGlyphPositions', {1, 1, 'abc'}, {[1, 1], []});
    % PsychNanoVG('TextLetterSpacing', spacing)
    tcall('TextLetterSpacing', {1}, {});
    % PsychNanoVG('TextLineHeight', lineHeight)
    tcall('TextLineHeight', {1}, {});
    % [ascender, descender, lineh] = PsychNanoVG('TextMetrics')
    tcall('TextMetrics', {}, {[1, 1], [1, 1], [1, 1]});
    % color = PsychNanoVG('TransRGBA', c0, a)
    tcall('TransRGBA', {[1 0.5 0.25 1], 128}, {[1, 4]});
    % color = PsychNanoVG('TransRGBAf', c0, a)
    tcall('TransRGBAf', {[1 0.5 0.25 1], 1}, {[1, 4]});
    % PsychNanoVG('Transform', a, b, c, d, e, f)
    tcall('Transform', {1, 1, 1, 1, 1, 1}, {});
    % dst = PsychNanoVG('TransformIdentity')
    tcall('TransformIdentity', {}, {[1, 6]});
    % [dst, value] = PsychNanoVG('TransformInverse', src)
    tcall('TransformInverse', {[1 0 0 1 0 0]}, {[1, 6], [1, 1]});
    % dst = PsychNanoVG('TransformMultiply', dst, src)
    tcall('TransformMultiply', {[1 0 0 1 0 0], [1 0 0 1 0 0]}, {[1, 6]});
    % dstxdsty = PsychNanoVG('TransformPoint', xform, srcx, srcy)
    tcall('TransformPoint', {[1 0 0 1 0 0], 1, 1}, {[1, 2]});
    % dst = PsychNanoVG('TransformPremultiply', dst, src)
    tcall('TransformPremultiply', {[1 0 0 1 0 0], [1 0 0 1 0 0]}, {[1, 6]});
    % dst = PsychNanoVG('TransformRotate', a)
    tcall('TransformRotate', {1}, {[1, 6]});
    % dst = PsychNanoVG('TransformScale', sx, sy)
    tcall('TransformScale', {1, 1}, {[1, 6]});
    % dst = PsychNanoVG('TransformSkewX', a)
    tcall('TransformSkewX', {1}, {[1, 6]});
    % dst = PsychNanoVG('TransformSkewY', a)
    tcall('TransformSkewY', {1}, {[1, 6]});
    % dst = PsychNanoVG('TransformTranslate', tx, ty)
    tcall('TransformTranslate', {1, 1}, {[1, 6]});
    % PsychNanoVG('Translate', x, y)
    tcall('Translate', {1, 1}, {});
    % PsychNanoVG('UpdateImage', image, data)
    tcall('UpdateImage', {img, zeros(8, 8, 4, 'uint8')}, {});

    PsychNanoVG('CancelFrame');
end

function tcall(name, args, want)
%   want{k} is [rows cols] for output k, or [] for any size.
    global TST_PASS TST_FAIL %#ok<GVMIS>
    try
        if isempty(want)
            PsychNanoVG(name, args{:});
            good = true;
        else
            outs = cell(1, numel(want));
            [outs{:}] = PsychNanoVG(name, args{:});
            good = true;
            for k = 1:numel(want)
                w = want{k};
                if isempty(w); continue; end
                if ~isequal(size(outs{k}), w); good = false; end
            end
        end
        if good
            TST_PASS = TST_PASS + 1;
        else
            TST_FAIL = TST_FAIL + 1;
            fprintf(2, '  FAIL  gen %s output size\n', name);
        end
    catch e
        TST_FAIL = TST_FAIL + 1;
        fprintf(2, '  FAIL  gen %s: %s\n', name, e.message);
    end
end
