/* Generated by gen/generate.py from third_party/nanovg/src/nanovg.h.
 * Do not edit. Run `build.m gen` to regenerate. */

#include "pnvg_internal.h"

/* Hand-written handlers, defined in psychnanovg.c, pnvg_batch.c, pnvg_targets.c. */
extern void h_BeginFrame(int, mxArray **, int, const mxArray **);
extern void h_CancelFrame(int, mxArray **, int, const mxArray **);
extern void h_Circles(int, mxArray **, int, const mxArray **);
extern void h_CreateImageFromTexture(int, mxArray **, int, const mxArray **);
extern void h_Enum(int, mxArray **, int, const mxArray **);
extern void h_EndFrame(int, mxArray **, int, const mxArray **);
extern void h_FindSystemFont(int, mxArray **, int, const mxArray **);
extern void h_Init(int, mxArray **, int, const mxArray **);
extern void h_Opcode(int, mxArray **, int, const mxArray **);
extern void h_PaintDelete(int, mxArray **, int, const mxArray **);
extern void h_Path(int, mxArray **, int, const mxArray **);
extern void h_Polygon(int, mxArray **, int, const mxArray **);
extern void h_Polyline(int, mxArray **, int, const mxArray **);
extern void h_Rects(int, mxArray **, int, const mxArray **);
extern void h_RenderTargetBind(int, mxArray **, int, const mxArray **);
extern void h_RenderTargetCreate(int, mxArray **, int, const mxArray **);
extern void h_RenderTargetDelete(int, mxArray **, int, const mxArray **);
extern void h_RenderTargetImage(int, mxArray **, int, const mxArray **);
extern void h_RenderTargetUnbind(int, mxArray **, int, const mxArray **);
extern void h_ResetFallbackFonts(int, mxArray **, int, const mxArray **);
extern void h_SetContext(int, mxArray **, int, const mxArray **);
extern void h_Shutdown(int, mxArray **, int, const mxArray **);
extern void h_Stats(int, mxArray **, int, const mxArray **);
extern void h_StrokeSegments(int, mxArray **, int, const mxArray **);
extern void h_Version(int, mxArray **, int, const mxArray **);

static void h_AddFallbackFont(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    pnvg_str s_baseFont;
    pnvg_str s_fallbackFont;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_string(prhs[0], 0, "AddFallbackFont", &s_baseFont);
    pnvg_arg_string(prhs[1], 1, "AddFallbackFont", &s_fallbackFont);
    ret = nvgAddFallbackFont(PNVG_VG, s_baseFont.p, s_fallbackFont.p);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    pnvg_str_free(&s_baseFont);
    pnvg_str_free(&s_fallbackFont);
}

static void h_AddFallbackFontId(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int baseFont;
    int fallbackFont;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    baseFont = pnvg_arg_font(prhs[0], 0, "AddFallbackFontId");
    fallbackFont = pnvg_arg_font(prhs[1], 1, "AddFallbackFontId");
    ret = nvgAddFallbackFontId(PNVG_VG, baseFont, fallbackFont);
    plhs[0] = mxCreateDoubleScalar((double)ret);
}

static void h_Arc(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float cx;
    float cy;
    float r;
    float a0;
    float a1;
    int dir;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    cx = pnvg_arg_float(prhs[0], 0, "Arc");
    cy = pnvg_arg_float(prhs[1], 1, "Arc");
    r = pnvg_arg_float(prhs[2], 2, "Arc");
    a0 = pnvg_arg_float(prhs[3], 3, "Arc");
    a1 = pnvg_arg_float(prhs[4], 4, "Arc");
    dir = pnvg_arg_enum(prhs[5], 5, "Arc");
    nvgArc(PNVG_VG, cx, cy, r, a0, a1, dir);
}

static void h_ArcTo(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x1;
    float y1;
    float x2;
    float y2;
    float radius;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x1 = pnvg_arg_float(prhs[0], 0, "ArcTo");
    y1 = pnvg_arg_float(prhs[1], 1, "ArcTo");
    x2 = pnvg_arg_float(prhs[2], 2, "ArcTo");
    y2 = pnvg_arg_float(prhs[3], 3, "ArcTo");
    radius = pnvg_arg_float(prhs[4], 4, "ArcTo");
    nvgArcTo(PNVG_VG, x1, y1, x2, y2, radius);
}

static void h_BeginPath(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgBeginPath(PNVG_VG);
}

static void h_BezierTo(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float c1x;
    float c1y;
    float c2x;
    float c2y;
    float x;
    float y;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    c1x = pnvg_arg_float(prhs[0], 0, "BezierTo");
    c1y = pnvg_arg_float(prhs[1], 1, "BezierTo");
    c2x = pnvg_arg_float(prhs[2], 2, "BezierTo");
    c2y = pnvg_arg_float(prhs[3], 3, "BezierTo");
    x = pnvg_arg_float(prhs[4], 4, "BezierTo");
    y = pnvg_arg_float(prhs[5], 5, "BezierTo");
    nvgBezierTo(PNVG_VG, c1x, c1y, c2x, c2y, x, y);
}

static void h_BoxGradient(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    float w;
    float h;
    float r;
    float f;
    NVGcolor icol;
    NVGcolor ocol;
    NVGpaint ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "BoxGradient");
    y = pnvg_arg_float(prhs[1], 1, "BoxGradient");
    w = pnvg_arg_float(prhs[2], 2, "BoxGradient");
    h = pnvg_arg_float(prhs[3], 3, "BoxGradient");
    r = pnvg_arg_float(prhs[4], 4, "BoxGradient");
    f = pnvg_arg_float(prhs[5], 5, "BoxGradient");
    icol = pnvg_arg_color(prhs[6], 6, "BoxGradient");
    ocol = pnvg_arg_color(prhs[7], 7, "BoxGradient");
    ret = nvgBoxGradient(PNVG_VG, x, y, w, h, r, f, icol, ocol);
    plhs[0] = mxCreateDoubleScalar((double)pnvg_paint_store(&ret));
}

static void h_Circle(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float cx;
    float cy;
    float r;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    cx = pnvg_arg_float(prhs[0], 0, "Circle");
    cy = pnvg_arg_float(prhs[1], 1, "Circle");
    r = pnvg_arg_float(prhs[2], 2, "Circle");
    nvgCircle(PNVG_VG, cx, cy, r);
}

static void h_ClosePath(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgClosePath(PNVG_VG);
}

static void h_CreateFont(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    pnvg_str s_name;
    pnvg_str s_filename;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_string(prhs[0], 0, "CreateFont", &s_name);
    pnvg_arg_string(prhs[1], 1, "CreateFont", &s_filename);
    ret = nvgCreateFont(PNVG_VG, s_name.p, s_filename.p);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    pnvg_str_free(&s_name);
    pnvg_str_free(&s_filename);
}

static void h_CreateFontAtIndex(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    pnvg_str s_name;
    pnvg_str s_filename;
    int fontIndex;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_string(prhs[0], 0, "CreateFontAtIndex", &s_name);
    pnvg_arg_string(prhs[1], 1, "CreateFontAtIndex", &s_filename);
    fontIndex = pnvg_arg_int(prhs[2], 2, "CreateFontAtIndex");
    ret = nvgCreateFontAtIndex(PNVG_VG, s_name.p, s_filename.p, fontIndex);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    pnvg_str_free(&s_name);
    pnvg_str_free(&s_filename);
}

static void h_CreateFontMem(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    pnvg_str s_name;
    const unsigned char *data;
    int n_data;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_string(prhs[0], 0, "CreateFontMem", &s_name);
    data = pnvg_arg_bytes(prhs[1], 1, "CreateFontMem", &n_data);
    ret = nvgCreateFontMem(PNVG_VG, s_name.p, (unsigned char *)data, n_data, 0);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    pnvg_str_free(&s_name);
}

static void h_CreateFontMemAtIndex(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    pnvg_str s_name;
    const unsigned char *data;
    int n_data;
    int fontIndex;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_string(prhs[0], 0, "CreateFontMemAtIndex", &s_name);
    data = pnvg_arg_bytes(prhs[1], 1, "CreateFontMemAtIndex", &n_data);
    fontIndex = pnvg_arg_int(prhs[2], 2, "CreateFontMemAtIndex");
    ret = nvgCreateFontMemAtIndex(PNVG_VG, s_name.p, (unsigned char *)data, n_data, 0, fontIndex);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    pnvg_str_free(&s_name);
}

static void h_CreateImage(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    pnvg_str s_filename;
    int imageFlags;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_string(prhs[0], 0, "CreateImage", &s_filename);
    imageFlags = pnvg_arg_enum(prhs[1], 1, "CreateImage");
    ret = nvgCreateImage(PNVG_VG, s_filename.p, imageFlags);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    pnvg_str_free(&s_filename);
}

static void h_CreateImageMem(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int imageFlags;
    const unsigned char *data;
    int n_data;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    imageFlags = pnvg_arg_enum(prhs[0], 0, "CreateImageMem");
    data = pnvg_arg_bytes(prhs[1], 1, "CreateImageMem", &n_data);
    ret = nvgCreateImageMem(PNVG_VG, imageFlags, (unsigned char *)data, n_data);
    plhs[0] = mxCreateDoubleScalar((double)ret);
}

static void h_CreateImageRGBA(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int imageFlags;
    const unsigned char *data;
    int imgw = 0, imgh = 0;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    imageFlags = pnvg_arg_enum(prhs[0], 0, "CreateImageRGBA");
    data = pnvg_arg_image_data(prhs[1], 1, "CreateImageRGBA", &imgw, &imgh);
    ret = nvgCreateImageRGBA(PNVG_VG, imgw, imgh, imageFlags, data);
    plhs[0] = mxCreateDoubleScalar((double)ret);
}

static void h_CurrentTransform(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float xform[6] = {1,0,0,1,0,0};
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgCurrentTransform(PNVG_VG, xform);
    plhs[0] = pnvg_make_row(xform, 6);
}

static void h_DegToRad(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float deg;
    float ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    deg = pnvg_arg_float(prhs[0], 0, "DegToRad");
    ret = nvgDegToRad(deg);
    plhs[0] = mxCreateDoubleScalar((double)ret);
}

static void h_DeleteImage(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int image;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    image = pnvg_arg_image(prhs[0], 0, "DeleteImage");
    nvgDeleteImage(PNVG_VG, image);
}

static void h_Ellipse(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float cx;
    float cy;
    float rx;
    float ry;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    cx = pnvg_arg_float(prhs[0], 0, "Ellipse");
    cy = pnvg_arg_float(prhs[1], 1, "Ellipse");
    rx = pnvg_arg_float(prhs[2], 2, "Ellipse");
    ry = pnvg_arg_float(prhs[3], 3, "Ellipse");
    nvgEllipse(PNVG_VG, cx, cy, rx, ry);
}

static void h_Fill(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgFill(PNVG_VG);
}

static void h_FillColor(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    NVGcolor color;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    color = pnvg_arg_color(prhs[0], 0, "FillColor");
    nvgFillColor(PNVG_VG, color);
}

static void h_FillPaint(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    NVGpaint paint;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    paint = pnvg_arg_paint(prhs[0], 0, "FillPaint");
    nvgFillPaint(PNVG_VG, paint);
}

static void h_FindFont(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    pnvg_str s_name;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_string(prhs[0], 0, "FindFont", &s_name);
    ret = nvgFindFont(PNVG_VG, s_name.p);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    pnvg_str_free(&s_name);
}

static void h_FontBlur(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float blur;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    blur = pnvg_arg_float(prhs[0], 0, "FontBlur");
    nvgFontBlur(PNVG_VG, blur);
}

static void h_FontFace(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    pnvg_str s_font;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_string(prhs[0], 0, "FontFace", &s_font);
    nvgFontFace(PNVG_VG, s_font.p);
    pnvg_str_free(&s_font);
}

static void h_FontFaceId(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int font;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    font = pnvg_arg_font(prhs[0], 0, "FontFaceId");
    nvgFontFaceId(PNVG_VG, font);
}

static void h_FontSize(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float size;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    size = pnvg_arg_float(prhs[0], 0, "FontSize");
    nvgFontSize(PNVG_VG, size);
}

static void h_GlobalAlpha(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float alpha;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    alpha = pnvg_arg_float(prhs[0], 0, "GlobalAlpha");
    nvgGlobalAlpha(PNVG_VG, alpha);
}

static void h_GlobalCompositeBlendFunc(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int sfactor;
    int dfactor;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    sfactor = pnvg_arg_enum(prhs[0], 0, "GlobalCompositeBlendFunc");
    dfactor = pnvg_arg_enum(prhs[1], 1, "GlobalCompositeBlendFunc");
    nvgGlobalCompositeBlendFunc(PNVG_VG, sfactor, dfactor);
}

static void h_GlobalCompositeBlendFuncSeparate(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int srcRGB;
    int dstRGB;
    int srcAlpha;
    int dstAlpha;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    srcRGB = pnvg_arg_enum(prhs[0], 0, "GlobalCompositeBlendFuncSeparate");
    dstRGB = pnvg_arg_enum(prhs[1], 1, "GlobalCompositeBlendFuncSeparate");
    srcAlpha = pnvg_arg_enum(prhs[2], 2, "GlobalCompositeBlendFuncSeparate");
    dstAlpha = pnvg_arg_enum(prhs[3], 3, "GlobalCompositeBlendFuncSeparate");
    nvgGlobalCompositeBlendFuncSeparate(PNVG_VG, srcRGB, dstRGB, srcAlpha, dstAlpha);
}

static void h_GlobalCompositeOperation(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int op;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    op = pnvg_arg_enum(prhs[0], 0, "GlobalCompositeOperation");
    nvgGlobalCompositeOperation(PNVG_VG, op);
}

static void h_HSL(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float h;
    float s;
    float l;
    NVGcolor ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    h = pnvg_arg_float(prhs[0], 0, "HSL");
    s = pnvg_arg_float(prhs[1], 1, "HSL");
    l = pnvg_arg_float(prhs[2], 2, "HSL");
    ret = nvgHSL(h, s, l);
    plhs[0] = pnvg_make_color(ret);
}

static void h_HSLA(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float h;
    float s;
    float l;
    unsigned char a;
    NVGcolor ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    h = pnvg_arg_float(prhs[0], 0, "HSLA");
    s = pnvg_arg_float(prhs[1], 1, "HSLA");
    l = pnvg_arg_float(prhs[2], 2, "HSLA");
    a = pnvg_arg_uchar(prhs[3], 3, "HSLA");
    ret = nvgHSLA(h, s, l, a);
    plhs[0] = pnvg_make_color(ret);
}

static void h_ImagePattern(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float ox;
    float oy;
    float ex;
    float ey;
    float angle;
    int image;
    float alpha;
    NVGpaint ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    ox = pnvg_arg_float(prhs[0], 0, "ImagePattern");
    oy = pnvg_arg_float(prhs[1], 1, "ImagePattern");
    ex = pnvg_arg_float(prhs[2], 2, "ImagePattern");
    ey = pnvg_arg_float(prhs[3], 3, "ImagePattern");
    angle = pnvg_arg_float(prhs[4], 4, "ImagePattern");
    image = pnvg_arg_image(prhs[5], 5, "ImagePattern");
    alpha = pnvg_arg_float(prhs[6], 6, "ImagePattern");
    ret = nvgImagePattern(PNVG_VG, ox, oy, ex, ey, angle, image, alpha);
    plhs[0] = mxCreateDoubleScalar((double)pnvg_paint_store(&ret));
}

static void h_ImageSize(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int image;
    int w = 0;
    int h = 0;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    image = pnvg_arg_image(prhs[0], 0, "ImageSize");
    nvgImageSize(PNVG_VG, image, &w, &h);
    {
        float pair_[2];
        pair_[0] = (float)w; pair_[1] = (float)h;
        plhs[0] = pnvg_make_row(pair_, 2);
    }
}

static void h_IntersectScissor(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    float w;
    float h;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "IntersectScissor");
    y = pnvg_arg_float(prhs[1], 1, "IntersectScissor");
    w = pnvg_arg_float(prhs[2], 2, "IntersectScissor");
    h = pnvg_arg_float(prhs[3], 3, "IntersectScissor");
    nvgIntersectScissor(PNVG_VG, x, y, w, h);
}

static void h_LerpRGBA(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    NVGcolor c0;
    NVGcolor c1;
    float u;
    NVGcolor ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    c0 = pnvg_arg_color(prhs[0], 0, "LerpRGBA");
    c1 = pnvg_arg_color(prhs[1], 1, "LerpRGBA");
    u = pnvg_arg_float(prhs[2], 2, "LerpRGBA");
    ret = nvgLerpRGBA(c0, c1, u);
    plhs[0] = pnvg_make_color(ret);
}

static void h_LineCap(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int cap;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    cap = pnvg_arg_enum(prhs[0], 0, "LineCap");
    nvgLineCap(PNVG_VG, cap);
}

static void h_LineJoin(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int join;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    join = pnvg_arg_enum(prhs[0], 0, "LineJoin");
    nvgLineJoin(PNVG_VG, join);
}

static void h_LineTo(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "LineTo");
    y = pnvg_arg_float(prhs[1], 1, "LineTo");
    nvgLineTo(PNVG_VG, x, y);
}

static void h_LinearGradient(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float sx;
    float sy;
    float ex;
    float ey;
    NVGcolor icol;
    NVGcolor ocol;
    NVGpaint ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    sx = pnvg_arg_float(prhs[0], 0, "LinearGradient");
    sy = pnvg_arg_float(prhs[1], 1, "LinearGradient");
    ex = pnvg_arg_float(prhs[2], 2, "LinearGradient");
    ey = pnvg_arg_float(prhs[3], 3, "LinearGradient");
    icol = pnvg_arg_color(prhs[4], 4, "LinearGradient");
    ocol = pnvg_arg_color(prhs[5], 5, "LinearGradient");
    ret = nvgLinearGradient(PNVG_VG, sx, sy, ex, ey, icol, ocol);
    plhs[0] = mxCreateDoubleScalar((double)pnvg_paint_store(&ret));
}

static void h_MiterLimit(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float limit;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    limit = pnvg_arg_float(prhs[0], 0, "MiterLimit");
    nvgMiterLimit(PNVG_VG, limit);
}

static void h_MoveTo(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "MoveTo");
    y = pnvg_arg_float(prhs[1], 1, "MoveTo");
    nvgMoveTo(PNVG_VG, x, y);
}

static void h_PathWinding(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int dir;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    dir = pnvg_arg_enum(prhs[0], 0, "PathWinding");
    nvgPathWinding(PNVG_VG, dir);
}

static void h_QuadTo(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float cx;
    float cy;
    float x;
    float y;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    cx = pnvg_arg_float(prhs[0], 0, "QuadTo");
    cy = pnvg_arg_float(prhs[1], 1, "QuadTo");
    x = pnvg_arg_float(prhs[2], 2, "QuadTo");
    y = pnvg_arg_float(prhs[3], 3, "QuadTo");
    nvgQuadTo(PNVG_VG, cx, cy, x, y);
}

static void h_RGB(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    unsigned char r;
    unsigned char g;
    unsigned char b;
    NVGcolor ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    r = pnvg_arg_uchar(prhs[0], 0, "RGB");
    g = pnvg_arg_uchar(prhs[1], 1, "RGB");
    b = pnvg_arg_uchar(prhs[2], 2, "RGB");
    ret = nvgRGB(r, g, b);
    plhs[0] = pnvg_make_color(ret);
}

static void h_RGBA(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    unsigned char r;
    unsigned char g;
    unsigned char b;
    unsigned char a;
    NVGcolor ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    r = pnvg_arg_uchar(prhs[0], 0, "RGBA");
    g = pnvg_arg_uchar(prhs[1], 1, "RGBA");
    b = pnvg_arg_uchar(prhs[2], 2, "RGBA");
    a = pnvg_arg_uchar(prhs[3], 3, "RGBA");
    ret = nvgRGBA(r, g, b, a);
    plhs[0] = pnvg_make_color(ret);
}

static void h_RGBAf(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float r;
    float g;
    float b;
    float a;
    NVGcolor ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    r = pnvg_arg_float(prhs[0], 0, "RGBAf");
    g = pnvg_arg_float(prhs[1], 1, "RGBAf");
    b = pnvg_arg_float(prhs[2], 2, "RGBAf");
    a = pnvg_arg_float(prhs[3], 3, "RGBAf");
    ret = nvgRGBAf(r, g, b, a);
    plhs[0] = pnvg_make_color(ret);
}

static void h_RGBf(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float r;
    float g;
    float b;
    NVGcolor ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    r = pnvg_arg_float(prhs[0], 0, "RGBf");
    g = pnvg_arg_float(prhs[1], 1, "RGBf");
    b = pnvg_arg_float(prhs[2], 2, "RGBf");
    ret = nvgRGBf(r, g, b);
    plhs[0] = pnvg_make_color(ret);
}

static void h_RadToDeg(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float rad;
    float ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    rad = pnvg_arg_float(prhs[0], 0, "RadToDeg");
    ret = nvgRadToDeg(rad);
    plhs[0] = mxCreateDoubleScalar((double)ret);
}

static void h_RadialGradient(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float cx;
    float cy;
    float inr;
    float outr;
    NVGcolor icol;
    NVGcolor ocol;
    NVGpaint ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    cx = pnvg_arg_float(prhs[0], 0, "RadialGradient");
    cy = pnvg_arg_float(prhs[1], 1, "RadialGradient");
    inr = pnvg_arg_float(prhs[2], 2, "RadialGradient");
    outr = pnvg_arg_float(prhs[3], 3, "RadialGradient");
    icol = pnvg_arg_color(prhs[4], 4, "RadialGradient");
    ocol = pnvg_arg_color(prhs[5], 5, "RadialGradient");
    ret = nvgRadialGradient(PNVG_VG, cx, cy, inr, outr, icol, ocol);
    plhs[0] = mxCreateDoubleScalar((double)pnvg_paint_store(&ret));
}

static void h_Rect(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    float w;
    float h;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "Rect");
    y = pnvg_arg_float(prhs[1], 1, "Rect");
    w = pnvg_arg_float(prhs[2], 2, "Rect");
    h = pnvg_arg_float(prhs[3], 3, "Rect");
    nvgRect(PNVG_VG, x, y, w, h);
}

static void h_Reset(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgReset(PNVG_VG);
}

static void h_ResetFallbackFontsId(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int baseFont;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    baseFont = pnvg_arg_font(prhs[0], 0, "ResetFallbackFontsId");
    nvgResetFallbackFontsId(PNVG_VG, baseFont);
}

static void h_ResetScissor(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgResetScissor(PNVG_VG);
}

static void h_ResetTransform(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgResetTransform(PNVG_VG);
}

static void h_Restore(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgRestore(PNVG_VG);
}

static void h_Rotate(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float angle;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    angle = pnvg_arg_float(prhs[0], 0, "Rotate");
    nvgRotate(PNVG_VG, angle);
}

static void h_RoundedRect(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    float w;
    float h;
    float r;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "RoundedRect");
    y = pnvg_arg_float(prhs[1], 1, "RoundedRect");
    w = pnvg_arg_float(prhs[2], 2, "RoundedRect");
    h = pnvg_arg_float(prhs[3], 3, "RoundedRect");
    r = pnvg_arg_float(prhs[4], 4, "RoundedRect");
    nvgRoundedRect(PNVG_VG, x, y, w, h, r);
}

static void h_RoundedRectVarying(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    float w;
    float h;
    float radTopLeft;
    float radTopRight;
    float radBottomRight;
    float radBottomLeft;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "RoundedRectVarying");
    y = pnvg_arg_float(prhs[1], 1, "RoundedRectVarying");
    w = pnvg_arg_float(prhs[2], 2, "RoundedRectVarying");
    h = pnvg_arg_float(prhs[3], 3, "RoundedRectVarying");
    radTopLeft = pnvg_arg_float(prhs[4], 4, "RoundedRectVarying");
    radTopRight = pnvg_arg_float(prhs[5], 5, "RoundedRectVarying");
    radBottomRight = pnvg_arg_float(prhs[6], 6, "RoundedRectVarying");
    radBottomLeft = pnvg_arg_float(prhs[7], 7, "RoundedRectVarying");
    nvgRoundedRectVarying(PNVG_VG, x, y, w, h, radTopLeft, radTopRight, radBottomRight, radBottomLeft);
}

static void h_Save(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgSave(PNVG_VG);
}

static void h_Scale(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "Scale");
    y = pnvg_arg_float(prhs[1], 1, "Scale");
    nvgScale(PNVG_VG, x, y);
}

static void h_Scissor(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    float w;
    float h;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "Scissor");
    y = pnvg_arg_float(prhs[1], 1, "Scissor");
    w = pnvg_arg_float(prhs[2], 2, "Scissor");
    h = pnvg_arg_float(prhs[3], 3, "Scissor");
    nvgScissor(PNVG_VG, x, y, w, h);
}

static void h_ShapeAntiAlias(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int enabled;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    enabled = pnvg_arg_int(prhs[0], 0, "ShapeAntiAlias");
    nvgShapeAntiAlias(PNVG_VG, enabled);
}

static void h_SkewX(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float angle;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    angle = pnvg_arg_float(prhs[0], 0, "SkewX");
    nvgSkewX(PNVG_VG, angle);
}

static void h_SkewY(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float angle;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    angle = pnvg_arg_float(prhs[0], 0, "SkewY");
    nvgSkewY(PNVG_VG, angle);
}

static void h_Stroke(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgStroke(PNVG_VG);
}

static void h_StrokeColor(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    NVGcolor color;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    color = pnvg_arg_color(prhs[0], 0, "StrokeColor");
    nvgStrokeColor(PNVG_VG, color);
}

static void h_StrokePaint(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    NVGpaint paint;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    paint = pnvg_arg_paint(prhs[0], 0, "StrokePaint");
    nvgStrokePaint(PNVG_VG, paint);
}

static void h_StrokeWidth(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float size;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    size = pnvg_arg_float(prhs[0], 0, "StrokeWidth");
    nvgStrokeWidth(PNVG_VG, size);
}

static void h_Text(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    pnvg_str s_string;
    float ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "Text");
    y = pnvg_arg_float(prhs[1], 1, "Text");
    pnvg_arg_string(prhs[2], 2, "Text", &s_string);
    ret = nvgText(PNVG_VG, x, y, s_string.p, s_string.p + s_string.n);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    pnvg_str_free(&s_string);
}

static void h_TextAlign(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int align;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    align = pnvg_arg_enum(prhs[0], 0, "TextAlign");
    nvgTextAlign(PNVG_VG, align);
}

static void h_TextBounds(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    pnvg_str s_string;
    float bounds[4] = {0,0,0,0};
    float ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "TextBounds");
    y = pnvg_arg_float(prhs[1], 1, "TextBounds");
    pnvg_arg_string(prhs[2], 2, "TextBounds", &s_string);
    ret = nvgTextBounds(PNVG_VG, x, y, s_string.p, s_string.p + s_string.n, bounds);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    if (nlhs > 1) plhs[1] = pnvg_make_row(bounds, 4);
    pnvg_str_free(&s_string);
}

static void h_TextBox(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    float breakRowWidth;
    pnvg_str s_string;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "TextBox");
    y = pnvg_arg_float(prhs[1], 1, "TextBox");
    breakRowWidth = pnvg_arg_float(prhs[2], 2, "TextBox");
    pnvg_arg_string(prhs[3], 3, "TextBox", &s_string);
    nvgTextBox(PNVG_VG, x, y, breakRowWidth, s_string.p, s_string.p + s_string.n);
    pnvg_str_free(&s_string);
}

static void h_TextBoxBounds(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    float breakRowWidth;
    pnvg_str s_string;
    float bounds[4] = {0,0,0,0};
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "TextBoxBounds");
    y = pnvg_arg_float(prhs[1], 1, "TextBoxBounds");
    breakRowWidth = pnvg_arg_float(prhs[2], 2, "TextBoxBounds");
    pnvg_arg_string(prhs[3], 3, "TextBoxBounds", &s_string);
    nvgTextBoxBounds(PNVG_VG, x, y, breakRowWidth, s_string.p, s_string.p + s_string.n, bounds);
    plhs[0] = pnvg_make_row(bounds, 4);
    pnvg_str_free(&s_string);
}

static void h_TextBreakLines(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    pnvg_str s_string;
    float breakRowWidth;
    NVGtextRow row_buf[PNVG_MAX_ROWS];
    int max_rows;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_string(prhs[0], 0, "TextBreakLines", &s_string);
    breakRowWidth = pnvg_arg_float(prhs[1], 1, "TextBreakLines");
    max_rows = (nrhs > 2) ? pnvg_arg_int(prhs[2], 2, "TextBreakLines") : 64;
    if (max_rows < 1 || max_rows > PNVG_MAX_ROWS)
        pnvg_err("psychnanovg:Range", "TextBreakLines: maxRows must be 1 to %d", PNVG_MAX_ROWS);
    ret = nvgTextBreakLines(PNVG_VG, s_string.p, s_string.p + s_string.n, breakRowWidth, row_buf, max_rows);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    if (nlhs > 1) plhs[1] = pnvg_make_rows(row_buf, ret, s_string.p);
    pnvg_str_free(&s_string);
}

static void h_TextGlyphPositions(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    pnvg_str s_string;
    NVGglyphPosition pos_buf[PNVG_MAX_GLYPHS];
    int max_positions;
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "TextGlyphPositions");
    y = pnvg_arg_float(prhs[1], 1, "TextGlyphPositions");
    pnvg_arg_string(prhs[2], 2, "TextGlyphPositions", &s_string);
    max_positions = (int)s_string.n;
    if (max_positions > PNVG_MAX_GLYPHS) max_positions = PNVG_MAX_GLYPHS;
    ret = nvgTextGlyphPositions(PNVG_VG, x, y, s_string.p, s_string.p + s_string.n, pos_buf, max_positions);
    plhs[0] = mxCreateDoubleScalar((double)ret);
    if (nlhs > 1) plhs[1] = pnvg_make_glyphs(pos_buf, ret, s_string.p);
    pnvg_str_free(&s_string);
}

static void h_TextLetterSpacing(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float spacing;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    spacing = pnvg_arg_float(prhs[0], 0, "TextLetterSpacing");
    nvgTextLetterSpacing(PNVG_VG, spacing);
}

static void h_TextLineHeight(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float lineHeight;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    lineHeight = pnvg_arg_float(prhs[0], 0, "TextLineHeight");
    nvgTextLineHeight(PNVG_VG, lineHeight);
}

static void h_TextMetrics(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float ascender = 0.0f;
    float descender = 0.0f;
    float lineh = 0.0f;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgTextMetrics(PNVG_VG, &ascender, &descender, &lineh);
    plhs[0] = mxCreateDoubleScalar((double)ascender);
    if (nlhs > 1) plhs[1] = mxCreateDoubleScalar((double)descender);
    if (nlhs > 2) plhs[2] = mxCreateDoubleScalar((double)lineh);
}

static void h_TransRGBA(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    NVGcolor c0;
    unsigned char a;
    NVGcolor ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    c0 = pnvg_arg_color(prhs[0], 0, "TransRGBA");
    a = pnvg_arg_uchar(prhs[1], 1, "TransRGBA");
    ret = nvgTransRGBA(c0, a);
    plhs[0] = pnvg_make_color(ret);
}

static void h_TransRGBAf(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    NVGcolor c0;
    float a;
    NVGcolor ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    c0 = pnvg_arg_color(prhs[0], 0, "TransRGBAf");
    a = pnvg_arg_float(prhs[1], 1, "TransRGBAf");
    ret = nvgTransRGBAf(c0, a);
    plhs[0] = pnvg_make_color(ret);
}

static void h_Transform(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float a;
    float b;
    float c;
    float d;
    float e;
    float f;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    a = pnvg_arg_float(prhs[0], 0, "Transform");
    b = pnvg_arg_float(prhs[1], 1, "Transform");
    c = pnvg_arg_float(prhs[2], 2, "Transform");
    d = pnvg_arg_float(prhs[3], 3, "Transform");
    e = pnvg_arg_float(prhs[4], 4, "Transform");
    f = pnvg_arg_float(prhs[5], 5, "Transform");
    nvgTransform(PNVG_VG, a, b, c, d, e, f);
}

static void h_TransformIdentity(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dst[6] = {1,0,0,1,0,0};
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    nvgTransformIdentity(dst);
    plhs[0] = pnvg_make_row(dst, 6);
}

static void h_TransformInverse(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dst[6] = {1,0,0,1,0,0};
    float src[6];
    int ret;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_xform(prhs[0], 0, "TransformInverse", src);
    ret = nvgTransformInverse(dst, src);
    plhs[0] = pnvg_make_row(dst, 6);
    if (nlhs > 1) plhs[1] = mxCreateDoubleScalar((double)ret);
}

static void h_TransformMultiply(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dst[6];
    float src[6];
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_xform(prhs[0], 0, "TransformMultiply", dst);
    pnvg_arg_xform(prhs[1], 1, "TransformMultiply", src);
    nvgTransformMultiply(dst, src);
    plhs[0] = pnvg_make_row(dst, 6);
}

static void h_TransformPoint(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dstx = 0.0f;
    float dsty = 0.0f;
    float xform[6];
    float srcx;
    float srcy;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_xform(prhs[0], 0, "TransformPoint", xform);
    srcx = pnvg_arg_float(prhs[1], 1, "TransformPoint");
    srcy = pnvg_arg_float(prhs[2], 2, "TransformPoint");
    nvgTransformPoint(&dstx, &dsty, xform, srcx, srcy);
    {
        float pair_[2];
        pair_[0] = (float)dstx; pair_[1] = (float)dsty;
        plhs[0] = pnvg_make_row(pair_, 2);
    }
}

static void h_TransformPremultiply(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dst[6];
    float src[6];
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    pnvg_arg_xform(prhs[0], 0, "TransformPremultiply", dst);
    pnvg_arg_xform(prhs[1], 1, "TransformPremultiply", src);
    nvgTransformPremultiply(dst, src);
    plhs[0] = pnvg_make_row(dst, 6);
}

static void h_TransformRotate(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dst[6] = {1,0,0,1,0,0};
    float a;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    a = pnvg_arg_float(prhs[0], 0, "TransformRotate");
    nvgTransformRotate(dst, a);
    plhs[0] = pnvg_make_row(dst, 6);
}

static void h_TransformScale(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dst[6] = {1,0,0,1,0,0};
    float sx;
    float sy;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    sx = pnvg_arg_float(prhs[0], 0, "TransformScale");
    sy = pnvg_arg_float(prhs[1], 1, "TransformScale");
    nvgTransformScale(dst, sx, sy);
    plhs[0] = pnvg_make_row(dst, 6);
}

static void h_TransformSkewX(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dst[6] = {1,0,0,1,0,0};
    float a;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    a = pnvg_arg_float(prhs[0], 0, "TransformSkewX");
    nvgTransformSkewX(dst, a);
    plhs[0] = pnvg_make_row(dst, 6);
}

static void h_TransformSkewY(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dst[6] = {1,0,0,1,0,0};
    float a;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    a = pnvg_arg_float(prhs[0], 0, "TransformSkewY");
    nvgTransformSkewY(dst, a);
    plhs[0] = pnvg_make_row(dst, 6);
}

static void h_TransformTranslate(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float dst[6] = {1,0,0,1,0,0};
    float tx;
    float ty;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    tx = pnvg_arg_float(prhs[0], 0, "TransformTranslate");
    ty = pnvg_arg_float(prhs[1], 1, "TransformTranslate");
    nvgTransformTranslate(dst, tx, ty);
    plhs[0] = pnvg_make_row(dst, 6);
}

static void h_Translate(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    float x;
    float y;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    x = pnvg_arg_float(prhs[0], 0, "Translate");
    y = pnvg_arg_float(prhs[1], 1, "Translate");
    nvgTranslate(PNVG_VG, x, y);
}

static void h_UpdateImage(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    int image;
    const unsigned char *data;
    int imgw = 0, imgh = 0;
    (void)nlhs; (void)nrhs; (void)plhs; (void)prhs;
    image = pnvg_arg_image(prhs[0], 0, "UpdateImage");
    data = pnvg_arg_image_data(prhs[1], 1, "UpdateImage", &imgw, &imgh);
    nvgUpdateImage(PNVG_VG, image, data);
}

const pnvg_cmd pnvg_cmds[] = {
    { "AddFallbackFont", h_AddFallbackFont, 2, 2, 1, PNVG_F_INIT, "Text",
        "Adds a fallback font by name." },
    { "AddFallbackFontId", h_AddFallbackFontId, 2, 2, 1, PNVG_F_INIT, "Text",
        "Adds a fallback font by handle." },
    { "Arc", h_Arc, 6, 6, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Creates new circle arc shaped sub-path. The arc center is at "
        "cx,cy, the arc radius is r, and the arc is drawn from angle a0 "
        "to a1, and swept in direction dir (NVG_CCW, or NVG_CW). Angles "
        "are specified in radians." },
    { "ArcTo", h_ArcTo, 5, 5, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Adds an arc segment at the corner defined by the last path "
        "point, and two specified points." },
    { "BeginFrame", h_BeginFrame, 2, 3, 0, PNVG_F_INIT|PNVG_F_GL, "Lifecycle",
        "PsychNanoVG('BeginFrame', w, h [, pixelRatio=1]). Saves the "
        "viewport and the blend state, sets the viewport to the target "
        "size, and starts a frame." },
    { "BeginPath", h_BeginPath, 0, 0, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Paths Drawing a new shape starts with nvgBeginPath(), it clears "
        "all the currently defined paths. Then you define one or more "
        "paths and sub-paths which describe the shape. The are functions "
        "to draw common shapes like rectangles and circles, and lower "
        "level step-by-step functions, which allow to define a path curve "
        "by curve. NanoVG uses even-odd fill rule to draw the shapes. "
        "Solid shapes should have counter clockwise winding and holes "
        "should have counter clockwise order. To specify winding of a "
        "path you can call nvgPathWinding(). This is useful especially "
        "for the common shapes, which are drawn CCW. Finally you can fill "
        "the path using current fill style by calling nvgFill(), and "
        "stroke it with current stroke style by calling nvgStroke(). The "
        "curve segments and sub-paths are transformed by the current "
        "transform. Clears the current path and sub-paths." },
    { "BezierTo", h_BezierTo, 6, 6, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Adds cubic bezier segment from last point in the path via two "
        "control points to the specified point." },
    { "BoxGradient", h_BoxGradient, 8, 8, 1, PNVG_F_INIT, "Paints",
        "Creates and returns a box gradient. Box gradient is a feathered "
        "rounded rectangle, it is useful for rendering drop shadows or "
        "highlights for boxes. Parameters (x,y) define the top-left "
        "corner of the rectangle, (w,h) define the size of the rectangle, "
        "r defines the corner radius, and f feather. Feather defines how "
        "blurry the border of the rectangle is. Parameter icol specifies "
        "the inner color and ocol the outer color of the gradient. The "
        "gradient is transformed by the current transform when it is "
        "passed to nvgFillPaint() or nvgStrokePaint()." },
    { "CancelFrame", h_CancelFrame, 0, 0, 0, PNVG_F_INIT, "Lifecycle",
        "PsychNanoVG('CancelFrame'). Drops the current frame without "
        "drawing it." },
    { "Circle", h_Circle, 3, 3, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Creates new circle shaped sub-path." },
    { "Circles", h_Circles, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Batch",
        "PsychNanoVG('Circles', cxyr). Nx3 double or single. One Circle "
        "per row in one path, for dot fields." },
    { "ClosePath", h_ClosePath, 0, 0, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Closes current sub-path with a line segment." },
    { "CreateFont", h_CreateFont, 2, 2, 1, PNVG_F_MKFONT|PNVG_F_INIT|PNVG_F_GL, "Text",
        "Text NanoVG allows you to load .ttf files and use the font to "
        "render text. The appearance of the text can be defined by "
        "setting the current text style and by specifying the fill color. "
        "Common text and font settings such as font size, letter spacing "
        "and text align are supported. Font blur allows you to create "
        "simple text effects such as drop shadows. At render time the "
        "font face can be set based on the font handles or name. Font "
        "measure functions return values in local space, the calculations "
        "are carried in the same resolution as the final rendering. This "
        "is done because the text glyph positions are snapped to the "
        "nearest pixels sharp rendering. The local space means that "
        "values are not rotated or scale as per the current "
        "transformation. For example if you set font size to 12, which "
        "would mean that line height is 16, then regardless of the "
        "current scaling and rotation, the returned line height is always "
        "16. Some measures may vary because of the scaling since "
        "aforementioned pixel snapping. While this may sound a little "
        "odd, the setup allows you to always render the same way "
        "regardless of scaling. I.e. following works regardless of "
        "scaling: const char* txt = \"Text me up.\"; nvgTextBounds(vg, x,y, "
        "txt, NULL, bounds); nvgBeginPath(vg); nvgRect(vg, "
        "bounds[0],bounds[1], bounds[2]-bounds[0], bounds[3]-bounds[1]); "
        "nvgFill(vg); Note: currently only solid color fill is supported "
        "for text. Creates font by loading it from the disk from "
        "specified file name. Returns handle to the font." },
    { "CreateFontAtIndex", h_CreateFontAtIndex, 3, 3, 1, PNVG_F_MKFONT|PNVG_F_INIT|PNVG_F_GL, "Text",
        "fontIndex specifies which font face to load from a .ttf/.ttc "
        "file." },
    { "CreateFontMem", h_CreateFontMem, 2, 2, 1, PNVG_F_MKFONT|PNVG_F_INIT|PNVG_F_GL, "Text",
        "Creates font by loading it from the specified memory chunk. "
        "Returns handle to the font." },
    { "CreateFontMemAtIndex", h_CreateFontMemAtIndex, 3, 3, 1, PNVG_F_MKFONT|PNVG_F_INIT|PNVG_F_GL, "Text",
        "fontIndex specifies which font face to load from a .ttf/.ttc "
        "file." },
    { "CreateImage", h_CreateImage, 2, 2, 1, PNVG_F_MKIMG|PNVG_F_INIT|PNVG_F_GL, "Images",
        "Images NanoVG allows you to load jpg, png, psd, tga, pic and gif "
        "files to be used for rendering. In addition you can upload your "
        "own image. The image loading is provided by stb_image. The "
        "parameter imageFlags is combination of flags defined in "
        "NVGimageFlags. Creates image by loading it from the disk from "
        "specified file name. Returns handle to the image." },
    { "CreateImageFromTexture", h_CreateImageFromTexture, 3, 4, 1, PNVG_F_INIT|PNVG_F_GL, "Targets",
        "img = PsychNanoVG('CreateImageFromTexture', glTexId, w, h [, "
        "flags]). Wraps an existing GL texture, such as the id from "
        "Screen('GetOpenGLTexture'), as a NanoVG image." },
    { "CreateImageMem", h_CreateImageMem, 2, 2, 1, PNVG_F_MKIMG|PNVG_F_INIT|PNVG_F_GL, "Images",
        "Creates image by loading it from the specified chunk of memory. "
        "Returns handle to the image." },
    { "CreateImageRGBA", h_CreateImageRGBA, 2, 2, 1, PNVG_F_MKIMG|PNVG_F_INIT|PNVG_F_GL, "Images",
        "Creates image from specified image data. Returns handle to the "
        "image." },
    { "CurrentTransform", h_CurrentTransform, 0, 0, 1, PNVG_F_INIT|PNVG_F_FRAME, "Transforms",
        "Stores the top part (a-f) of the current transformation matrix "
        "in to the specified buffer. [a c e] [b d f] [0 0 1] There should "
        "be space for 6 floats in the return buffer for the values a-f." },
    { "DegToRad", h_DegToRad, 1, 1, 1, 0, "Transform helpers",
        "Converts degrees to radians and vice versa." },
    { "DeleteImage", h_DeleteImage, 1, 1, 0, PNVG_F_DELIMG|PNVG_F_INIT|PNVG_F_GL, "Images",
        "Deletes created image." },
    { "Ellipse", h_Ellipse, 4, 4, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Creates new ellipse shaped sub-path." },
    { "EndFrame", h_EndFrame, 0, 0, 0, PNVG_F_INIT|PNVG_F_GL, "Lifecycle",
        "PsychNanoVG('EndFrame'). Flushes the frame to GL, restores the "
        "saved GL state, drains GL errors, and records frame statistics." },
    { "Enum", h_Enum, 1, 1, 1, 0, "Lifecycle",
        "v = PsychNanoVG('Enum', 'NVG_ALIGN_CENTER'). Looks up a NanoVG "
        "constant. The NVG_ prefix is optional and names can be joined "
        "with |." },
    { "Fill", h_Fill, 0, 0, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Fills the current path with current fill style." },
    { "FillColor", h_FillColor, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets current fill style to a solid color." },
    { "FillPaint", h_FillPaint, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets current fill style to a paint, which can be a one of the "
        "gradients or a pattern." },
    { "FindFont", h_FindFont, 1, 1, 1, PNVG_F_INIT, "Text",
        "Finds a loaded font of specified name, and returns handle to it, "
        "or -1 if the font is not found." },
    { "FindSystemFont", h_FindSystemFont, 1, 1, 1, 0, "Lifecycle",
        "path = PsychNanoVG('FindSystemFont', 'Arial'). Searches the "
        "operating system font directories for a TTF or OTF file whose "
        "name matches, and returns '' when there is none. The search "
        "itself lives in PsychNanoVGFonts.m, so it is easy to extend." },
    { "FontBlur", h_FontBlur, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Sets the blur of current text style." },
    { "FontFace", h_FontFace, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Sets the font face based on specified name of current text "
        "style." },
    { "FontFaceId", h_FontFaceId, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Sets the font face based on specified id of current text style." },
    { "FontSize", h_FontSize, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Sets the font size of current text style." },
    { "GlobalAlpha", h_GlobalAlpha, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets the transparency applied to all rendered shapes. Already "
        "transparent paths will get proportionally more transparent as "
        "well." },
    { "GlobalCompositeBlendFunc", h_GlobalCompositeBlendFunc, 2, 2, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets the composite operation with custom pixel arithmetic. The "
        "parameters should be one of NVGblendFactor." },
    { "GlobalCompositeBlendFuncSeparate", h_GlobalCompositeBlendFuncSeparate, 4, 4, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets the composite operation with custom pixel arithmetic for "
        "RGB and alpha components separately. The parameters should be "
        "one of NVGblendFactor." },
    { "GlobalCompositeOperation", h_GlobalCompositeOperation, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Composite operation The composite operations in NanoVG are "
        "modeled after HTML Canvas API, and the blend func is based on "
        "OpenGL (see corresponding manuals for more info). The colors in "
        "the blending state have premultiplied alpha. Sets the composite "
        "operation. The op parameter should be one of "
        "NVGcompositeOperation." },
    { "HSL", h_HSL, 3, 3, 1, 0, "Colors",
        "Returns color value specified by hue, saturation and lightness. "
        "HSL values are all in range [0..1], alpha will be set to 255." },
    { "HSLA", h_HSLA, 4, 4, 1, 0, "Colors",
        "Returns color value specified by hue, saturation and lightness "
        "and alpha. HSL values are all in range [0..1], alpha in range "
        "[0..255]" },
    { "ImagePattern", h_ImagePattern, 7, 7, 1, PNVG_F_INIT, "Paints",
        "Creates and returns an image pattern. Parameters (ox,oy) specify "
        "the left-top location of the image pattern, (ex,ey) the size of "
        "one image, angle rotation around the top-left corner, image is "
        "handle to the image to render. The gradient is transformed by "
        "the current transform when it is passed to nvgFillPaint() or "
        "nvgStrokePaint()." },
    { "ImageSize", h_ImageSize, 1, 1, 1, PNVG_F_INIT|PNVG_F_GL, "Images",
        "Returns the dimensions of a created image." },
    { "Init", h_Init, 0, 1, 1, PNVG_F_GL, "Lifecycle",
        "ctx = PsychNanoVG('Init' [, opts]). Loads GL entry points, "
        "creates a context in the GL context that is current, makes it "
        "the current context, and returns its handle. One context per "
        "Psychtoolbox window. opts fields: antialias, stencilStrokes, "
        "debug, renderer ('auto', the backend of the build, or 'null' for "
        "tests)." },
    { "IntersectScissor", h_IntersectScissor, 4, 4, 0, PNVG_F_INIT|PNVG_F_FRAME, "Scissoring",
        "Intersects current scissor rectangle with the specified "
        "rectangle. The scissor rectangle is transformed by the current "
        "transform. Note: in case the rotation of previous scissor rect "
        "differs from the current one, the intersection will be done "
        "between the specified rectangle and the previous scissor "
        "rectangle transformed in the current transform space. The "
        "resulting shape is always rectangle." },
    { "LerpRGBA", h_LerpRGBA, 3, 3, 1, 0, "Colors",
        "Linearly interpolates from color c0 to c1, and returns resulting "
        "color value." },
    { "LineCap", h_LineCap, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets how the end of the line (cap) is drawn, Can be one of: "
        "NVG_BUTT (default), NVG_ROUND, NVG_SQUARE." },
    { "LineJoin", h_LineJoin, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets how sharp path corners are drawn. Can be one of NVG_MITER "
        "(default), NVG_ROUND, NVG_BEVEL." },
    { "LineTo", h_LineTo, 2, 2, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Adds line segment from the last point in the path to the "
        "specified point." },
    { "LinearGradient", h_LinearGradient, 6, 6, 1, PNVG_F_INIT, "Paints",
        "Paints NanoVG supports four types of paints: linear gradient, "
        "box gradient, radial gradient and image pattern. These can be "
        "used as paints for strokes and fills. Creates and returns a "
        "linear gradient. Parameters (sx,sy)-(ex,ey) specify the start "
        "and end coordinates of the linear gradient, icol specifies the "
        "start color and ocol the end color. The gradient is transformed "
        "by the current transform when it is passed to nvgFillPaint() or "
        "nvgStrokePaint()." },
    { "MiterLimit", h_MiterLimit, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets the miter limit of the stroke style. Miter limit controls "
        "when a sharp corner is beveled." },
    { "MoveTo", h_MoveTo, 2, 2, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Starts new sub-path with specified point as first point." },
    { "Opcode", h_Opcode, 1, 1, 1, 0, "Lifecycle",
        "op = PsychNanoVG('Opcode', 'LineTo'). The numeric opcode of a "
        "subcommand. Passing the opcode instead of the name skips the "
        "name lookup." },
    { "PaintDelete", h_PaintDelete, 1, 1, 0, PNVG_F_INIT, "Paints",
        "PsychNanoVG('PaintDelete', paint). Frees one paint table entry." },
    { "Path", h_Path, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Batch",
        "PsychNanoVG('Path', cmds). cmds is an Nx7 matrix with a command "
        "code in column 1 and its arguments after it, zero padded: 1 M x "
        "y, 2 L x y, 3 Q cx cy x y, 4 C c1x c1y c2x c2y x y, 5 Z, 6 Arc "
        "cx cy r a0 a1 dir, 7 ArcTo x1 y1 x2 y2 r, 8 Ellipse cx cy rx ry, "
        "9 Circle cx cy r, 10 Rect x y w h, 11 RoundedRect x y w h r, 12 "
        "Winding dir. Angles are radians; dir is 1 (CCW, SOLID) or 2 (CW, "
        "HOLE). Every row is checked before any is drawn. The same "
        "commands also go in a cell array, such as {{'M',x,y}, "
        "{'Arc',cx,cy,r,a0,a1,'CW'}, {'Z'}}. The matrix form is the fast "
        "path." },
    { "PathWinding", h_PathWinding, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Sets the current sub-path winding, see NVGwinding and "
        "NVGsolidity." },
    { "Polygon", h_Polygon, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Batch",
        "PsychNanoVG('Polygon', xy). Polyline with the path closed." },
    { "Polyline", h_Polyline, 1, 2, 0, PNVG_F_INIT|PNVG_F_FRAME, "Batch",
        "PsychNanoVG('Polyline', xy [, close=false]). xy is Nx2 double or "
        "single. MoveTo on the first row, LineTo on the rest. One MEX "
        "call for the whole path." },
    { "QuadTo", h_QuadTo, 4, 4, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Adds quadratic bezier segment from last point in the path via a "
        "control point to the specified point." },
    { "RGB", h_RGB, 3, 3, 1, 0, "Colors",
        "Color utils Colors in NanoVG are stored as unsigned ints in ABGR "
        "format. Returns a color value from red, green, blue values. "
        "Alpha will be set to 255 (1.0f)." },
    { "RGBA", h_RGBA, 4, 4, 1, 0, "Colors",
        "Returns a color value from red, green, blue and alpha values." },
    { "RGBAf", h_RGBAf, 4, 4, 1, 0, "Colors",
        "Returns a color value from red, green, blue and alpha values." },
    { "RGBf", h_RGBf, 3, 3, 1, 0, "Colors",
        "Returns a color value from red, green, blue values. Alpha will "
        "be set to 1.0f." },
    { "RadToDeg", h_RadToDeg, 1, 1, 1, 0, "Transform helpers",
        "RadToDeg." },
    { "RadialGradient", h_RadialGradient, 6, 6, 1, PNVG_F_INIT, "Paints",
        "Creates and returns a radial gradient. Parameters (cx,cy) "
        "specify the center, inr and outr specify the inner and outer "
        "radius of the gradient, icol specifies the start color and ocol "
        "the end color. The gradient is transformed by the current "
        "transform when it is passed to nvgFillPaint() or "
        "nvgStrokePaint()." },
    { "Rect", h_Rect, 4, 4, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Creates new rectangle shaped sub-path." },
    { "Rects", h_Rects, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Batch",
        "PsychNanoVG('Rects', xywh). Nx4 double or single, one Rect per "
        "row." },
    { "RenderTargetBind", h_RenderTargetBind, 1, 1, 0, PNVG_F_INIT|PNVG_F_GL, "Targets",
        "PsychNanoVG('RenderTargetBind', rt). Binds the target "
        "framebuffer. BeginFrame with the target size must follow." },
    { "RenderTargetCreate", h_RenderTargetCreate, 2, 3, 2, PNVG_F_INIT|PNVG_F_GL, "Targets",
        "[rt, glTexId] = PsychNanoVG('RenderTargetCreate', w, h [, "
        "imageFlags]). Pass glTexId to Screen('SetOpenGLTexture')." },
    { "RenderTargetDelete", h_RenderTargetDelete, 1, 1, 0, PNVG_F_INIT|PNVG_F_GL, "Targets",
        "PsychNanoVG('RenderTargetDelete', rt)." },
    { "RenderTargetImage", h_RenderTargetImage, 1, 1, 1, PNVG_F_INIT, "Targets",
        "img = PsychNanoVG('RenderTargetImage', rt). The NanoVG image id "
        "of the target, for ImagePattern." },
    { "RenderTargetUnbind", h_RenderTargetUnbind, 0, 0, 0, PNVG_F_INIT|PNVG_F_GL, "Targets",
        "PsychNanoVG('RenderTargetUnbind'). Rebinds the framebuffer that "
        "was current before RenderTargetBind." },
    { "Reset", h_Reset, 0, 0, 0, PNVG_F_INIT|PNVG_F_FRAME, "State",
        "Resets current render state to default values. Does not affect "
        "the render state stack." },
    { "ResetFallbackFonts", h_ResetFallbackFonts, 1, 1, 0, PNVG_F_INIT, "Text",
        "PsychNanoVG('ResetFallbackFonts', baseFont). Drops the fallback "
        "fonts of the named font. Raises psychnanovg:Handle when no font "
        "has that name." },
    { "ResetFallbackFontsId", h_ResetFallbackFontsId, 1, 1, 0, PNVG_F_INIT, "Text",
        "Resets fallback fonts by handle." },
    { "ResetScissor", h_ResetScissor, 0, 0, 0, PNVG_F_INIT|PNVG_F_FRAME, "Scissoring",
        "Reset and disables scissoring." },
    { "ResetTransform", h_ResetTransform, 0, 0, 0, PNVG_F_INIT|PNVG_F_FRAME, "Transforms",
        "Transforms The paths, gradients, patterns and scissor region are "
        "transformed by an transformation matrix at the time when they "
        "are passed to the API. The current transformation matrix is a "
        "affine matrix: [sx kx tx] [ky sy ty] [ 0 0 1] Where: sx,sy "
        "define scaling, kx,ky skewing, and tx,ty translation. The last "
        "row is assumed to be 0,0,1 and is not stored. Apart from "
        "nvgResetTransform(), each transformation function first creates "
        "specific transformation matrix and pre-multiplies the current "
        "transformation by it. Current coordinate system (transformation) "
        "can be saved and restored using nvgSave() and nvgRestore(). "
        "Resets current transform to a identity matrix." },
    { "Restore", h_Restore, 0, 0, 0, PNVG_F_INIT|PNVG_F_FRAME, "State",
        "Pops and restores current render state." },
    { "Rotate", h_Rotate, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Transforms",
        "Rotates current coordinate system. Angle is specified in "
        "radians." },
    { "RoundedRect", h_RoundedRect, 5, 5, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Creates new rounded rectangle shaped sub-path." },
    { "RoundedRectVarying", h_RoundedRectVarying, 8, 8, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Creates new rounded rectangle shaped sub-path with varying radii "
        "for each corner." },
    { "Save", h_Save, 0, 0, 0, PNVG_F_INIT|PNVG_F_FRAME, "State",
        "State Handling NanoVG contains state which represents how paths "
        "will be rendered. The state contains transform, fill and stroke "
        "styles, text and font styles, and scissor clipping. Pushes and "
        "saves the current render state into a state stack. A matching "
        "nvgRestore() must be used to restore the state." },
    { "Scale", h_Scale, 2, 2, 0, PNVG_F_INIT|PNVG_F_FRAME, "Transforms",
        "Scales the current coordinate system." },
    { "Scissor", h_Scissor, 4, 4, 0, PNVG_F_INIT|PNVG_F_FRAME, "Scissoring",
        "Scissoring Scissoring allows you to clip the rendering into a "
        "rectangle. This is useful for various user interface cases like "
        "rendering a text edit or a timeline. Sets the current scissor "
        "rectangle. The scissor rectangle is transformed by the current "
        "transform." },
    { "SetContext", h_SetContext, 0, 1, 1, 0, "Lifecycle",
        "prev = PsychNanoVG('SetContext', ctx). Makes ctx the current "
        "context and returns the handle that was current, 0 for none. "
        "Every other subcommand acts on the current context. "
        "PsychNanoVG('SetContext') with no handle returns the current one "
        "and changes nothing." },
    { "ShapeAntiAlias", h_ShapeAntiAlias, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Render styles Fill and stroke render style can be either a solid "
        "color or a paint which is a gradient or a pattern. Solid color "
        "is simply defined as a color value, different kinds of paints "
        "can be created using nvgLinearGradient(), nvgBoxGradient(), "
        "nvgRadialGradient() and nvgImagePattern(). Current render style "
        "can be saved and restored using nvgSave() and nvgRestore(). Sets "
        "whether to draw antialias for nvgStroke() and nvgFill(). It's "
        "enabled by default." },
    { "Shutdown", h_Shutdown, 0, 1, 0, 0, "Lifecycle",
        "PsychNanoVG('Shutdown' [, ctx]). Deletes the render targets, "
        "images, fonts, and NanoVG context of ctx, or of the current "
        "context. Call it inside Screen('BeginOpenGL') for the window of "
        "ctx. PsychNanoVG('Shutdown', 'all') deletes every context. The "
        "MEX file unlocks when no context is left." },
    { "SkewX", h_SkewX, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Transforms",
        "Skews the current coordinate system along X axis. Angle is "
        "specified in radians." },
    { "SkewY", h_SkewY, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Transforms",
        "Skews the current coordinate system along Y axis. Angle is "
        "specified in radians." },
    { "Stats", h_Stats, 0, 1, 1, 0, "Lifecycle",
        "s = PsychNanoVG('Stats' [, 'reset']). Per subcommand calls, "
        "totalNs, and maxNs, plus per frame endFrameNs, gpuNs, and NanoVG "
        "draw counters, all for the current context. gpuNs is NaN when "
        "the context has no GL timer queries." },
    { "Stroke", h_Stroke, 0, 0, 0, PNVG_F_INIT|PNVG_F_FRAME, "Paths",
        "Fills the current path with current stroke style." },
    { "StrokeColor", h_StrokeColor, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets current stroke style to a solid color." },
    { "StrokePaint", h_StrokePaint, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets current stroke style to a paint, which can be a one of the "
        "gradients or a pattern." },
    { "StrokeSegments", h_StrokeSegments, 2, 2, 0, PNVG_F_INIT|PNVG_F_FRAME, "Batch",
        "PsychNanoVG('StrokeSegments', seg, rgba). seg is Nx4 [x0 y0 x1 "
        "y1], rgba is Nx8 [r0 g0 b0 a0 r1 g1 b1 a1], double or single. "
        "Strokes each segment with a linear gradient from its first color "
        "to its second, with the current stroke width, cap, and join. "
        "Contiguous segments of one color become one stroke. Replaces the "
        "current path and keeps the stroke paint. See "
        "PsychNanoVGPolylineGradient." },
    { "StrokeWidth", h_StrokeWidth, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Render styles",
        "Sets the stroke width of the stroke style." },
    { "Text", h_Text, 3, 3, 1, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Draws text string at specified location. If end is specified "
        "only the sub-string up to the end is drawn." },
    { "TextAlign", h_TextAlign, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Sets the text align of current text style, see NVGalign for "
        "options." },
    { "TextBounds", h_TextBounds, 3, 3, 2, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Measures the specified text string. Parameter bounds should be a "
        "pointer to float[4], if the bounding box of the text should be "
        "returned. The bounds value are [xmin,ymin, xmax,ymax] Returns "
        "the horizontal advance of the measured text (i.e. where the next "
        "character should drawn). Measured values are returned in local "
        "coordinate space." },
    { "TextBox", h_TextBox, 4, 4, 0, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Draws multi-line text string at specified location wrapped at "
        "the specified width. If end is specified only the sub-string up "
        "to the end is drawn. White space is stripped at the beginning of "
        "the rows, the text is split at word boundaries or when new-line "
        "characters are encountered. Words longer than the max width are "
        "slit at nearest character (i.e. no hyphenation)." },
    { "TextBoxBounds", h_TextBoxBounds, 4, 4, 1, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Measures the specified multi-text string. Parameter bounds "
        "should be a pointer to float[4], if the bounding box of the text "
        "should be returned. The bounds value are [xmin,ymin, xmax,ymax] "
        "Measured values are returned in local coordinate space." },
    { "TextBreakLines", h_TextBreakLines, 2, 3, 2, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Breaks the specified text into lines. If end is specified only "
        "the sub-string will be used. White space is stripped at the "
        "beginning of the rows, the text is split at word boundaries or "
        "when new-line characters are encountered. Words longer than the "
        "max width are slit at nearest character (i.e. no hyphenation)." },
    { "TextGlyphPositions", h_TextGlyphPositions, 3, 3, 2, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Calculates the glyph x positions of the specified text. If end "
        "is specified only the sub-string will be used. Measured values "
        "are returned in local coordinate space." },
    { "TextLetterSpacing", h_TextLetterSpacing, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Sets the letter spacing of current text style." },
    { "TextLineHeight", h_TextLineHeight, 1, 1, 0, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Sets the proportional line height of current text style. The "
        "line height is specified as multiple of font size." },
    { "TextMetrics", h_TextMetrics, 0, 0, 3, PNVG_F_INIT|PNVG_F_FRAME, "Text",
        "Returns the vertical metrics based on the current text style. "
        "Measured values are returned in local coordinate space." },
    { "TransRGBA", h_TransRGBA, 2, 2, 1, 0, "Colors",
        "Sets transparency of a color value." },
    { "TransRGBAf", h_TransRGBAf, 2, 2, 1, 0, "Colors",
        "Sets transparency of a color value." },
    { "Transform", h_Transform, 6, 6, 0, PNVG_F_INIT|PNVG_F_FRAME, "Transforms",
        "Premultiplies current coordinate system by specified matrix. The "
        "parameters are interpreted as matrix as follows: [a c e] [b d f] "
        "[0 0 1]" },
    { "TransformIdentity", h_TransformIdentity, 0, 0, 1, 0, "Transform helpers",
        "The following functions can be used to make calculations on 2x3 "
        "transformation matrices. A 2x3 matrix is represented as "
        "float[6]. Sets the transform to identity matrix." },
    { "TransformInverse", h_TransformInverse, 1, 1, 2, 0, "Transform helpers",
        "Sets the destination to inverse of specified transform. Returns "
        "1 if the inverse could be calculated, else 0." },
    { "TransformMultiply", h_TransformMultiply, 2, 2, 1, 0, "Transform helpers",
        "Sets the transform to the result of multiplication of two "
        "transforms, of A = A*B." },
    { "TransformPoint", h_TransformPoint, 3, 3, 1, 0, "Transform helpers",
        "Transform a point by given transform." },
    { "TransformPremultiply", h_TransformPremultiply, 2, 2, 1, 0, "Transform helpers",
        "Sets the transform to the result of multiplication of two "
        "transforms, of A = B*A." },
    { "TransformRotate", h_TransformRotate, 1, 1, 1, 0, "Transform helpers",
        "Sets the transform to rotate matrix. Angle is specified in "
        "radians." },
    { "TransformScale", h_TransformScale, 2, 2, 1, 0, "Transform helpers",
        "Sets the transform to scale matrix." },
    { "TransformSkewX", h_TransformSkewX, 1, 1, 1, 0, "Transform helpers",
        "Sets the transform to skew-x matrix. Angle is specified in "
        "radians." },
    { "TransformSkewY", h_TransformSkewY, 1, 1, 1, 0, "Transform helpers",
        "Sets the transform to skew-y matrix. Angle is specified in "
        "radians." },
    { "TransformTranslate", h_TransformTranslate, 2, 2, 1, 0, "Transform helpers",
        "Sets the transform to translation matrix matrix." },
    { "Translate", h_Translate, 2, 2, 0, PNVG_F_INIT|PNVG_F_FRAME, "Transforms",
        "Translates current coordinate system." },
    { "UpdateImage", h_UpdateImage, 2, 2, 0, PNVG_F_INIT|PNVG_F_GL, "Images",
        "Updates image data specified by image handle." },
    { "Version", h_Version, 0, 0, 1, 0, "Lifecycle",
        "v = PsychNanoVG('Version'). Struct with nanovg, psychnanovg, "
        "backend, glVersion, glRenderer, build, context (the current "
        "handle, 0 for none), and contexts (every open handle)." },
};
const int pnvg_ncmds = 121;
const char *const pnvg_version_string = "0.2.0+nanovg.ce3bf745eb2d";
